### ISSUE TITLE
vultr centos 执行出错耶？

### ISSUE THREAD

**Issue by yechafengyun** [shellhub/shellhub#1]
2018-08-09 11:40:34 (45.8 MB/s) - “mt_proxy.sh” saved [3359/3359]

./mt_proxy.sh: line 25: ...: command not found

**Comment by shellhub** [comment]
`centos 7` or `centos 6`?

**Comment by yechafengyun** [comment]
centos 6

**Comment by shellhub** [comment]
先换成centos 7吧，代码暂时没支持旧版本centos 6，
![screenshot from 2018-08-17 16-32-14](https://user-images.githubusercontent.com/32572119/44256323-640ace00-a23b-11e8-85ac-c48fc4ddb72d.png)

**Comment by shellhub** [comment]
@yechafengyun Bug fixed `vultr.com centos 6`
