### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by Joe-LAI24** [shellhub/shellhub#2]
When Input secret i don input anything that it shows
Input secret (defalut: Auto Generated)
./mt_proxy.sh: line 113: xxd: command not found
and when it  finish that link can't how secret 
like  tg://proxy?server=172.96.250.241&port=413&secret=
the secret is empty

If i input the secret 
it shows it was finish but i can't connect，but i doesn't run.

and i find the install log  it show two error

nohup: appending output to `nohup.out'
nohup: failed to run command `./mtproto-proxy': No such file or directory

**Comment by shellhub** [comment]
I think you haven't install `xxd`
xxd is in the vim-common package
How to install?
``` bash
yum install vim-common # CentOS release
apt-get install vim-common # Debian or Ubuntu release
